CREATE TABLE CUSTOMER
(	ID NUMBER NOT NULL ENABLE,
     FIRST_NAME VARCHAR2(100) NOT NULL ENABLE,
     LAST_NAME VARCHAR2(100) NOT NULL ENABLE
);

CREATE OR REPLACE PACKAGE test_pkh
AS

    PROCEDURE tst_proc;
    FUNCTION tst_function(aN VARCHAR2 )
        return VARCHAR2;
    PROCEDURE proc_with_Param(Id NUMBER);
    FUNCTION tst_functionInt(aN NUMBER )
        return VARCHAR2;
END;
/
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES(1, 'Jack', 'Bauer');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES(2, 'Chloe', 'O''Brian');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES(3, 'Kim', 'Bauer');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES(4, 'David', 'Palmer');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES(5, 'Michelle', 'Dessler');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES(6, 'Jack', 'Bauer');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES(7, 'Chloe', 'O''Brian');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES(8, 'Kim', 'Bauer');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES(9, 'David', 'Palmer');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES(10, 'Michelle', 'Dessler');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES(11, 'Jack', 'Bauer');

CREATE OR REPLACE PACKAGE BODY test_pkh
IS

    PROCEDURE tst_proc
        is
    BEGIN
        NULL;
    END;
    FUNCTION tst_function(aN VARCHAR2  ) return VARCHAR2
        is
    BEGIN
        RETURN 1;
    END;
    PROCEDURE proc_with_Param(Id NUMBER)
        IS
    BEGIN
        NULL;
    END;
    FUNCTION tst_functionInt(aN Number )
        return VARCHAR2
        is
    BEGIN
        RETURN 1;
    END;
END;
/